apiVersion: v1
kind: Service
metadata:
  name: dev-restserver
  labels:
    tier: backend
spec:
  selector:
    app: dev-restserver
    tier: backend
  ports:
    - port: 8080
      nodePort: 8081
      name: http
  type: NodePort
