apiVersion: v1
kind: Service
metadata:
  name: dev-restserver
  labels:
    tier: backend
spec:
  selector:
    app: dev-restserver
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
